# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 838)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Tabs.setFont(font)
        self.Tabs.setAutoFillBackground(True)
        self.Tabs.setStyleSheet("QGroupBox { border: 1px solid grey;   border-radius: 10px;   font-weight: bold; font-size: 12pt; color: black; padding:8px; margin:8px; background-color: #F0F0F0;}\n"
"QGroupBox::title {  subcontrol-origin: margin;   subcontrol-position: top center;    padding:  0 5px;  }\n"
"QSpinBox {             background-color: #FFFFFF; }\n"
"QDoubleSpinBox {background-color: #FFFFFF;} \n"
"")
        self.Tabs.setObjectName("Tabs")
        self.tab_CF = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_CF.setFont(font)
        self.tab_CF.setObjectName("tab_CF")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_CF)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Select_CH0 = QtWidgets.QRadioButton(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Select_CH0.setFont(font)
        self.Select_CH0.setObjectName("Select_CH0")
        self.verticalLayout_3.addWidget(self.Select_CH0, 0, QtCore.Qt.AlignHCenter)
        self.Select_CH1 = QtWidgets.QRadioButton(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Select_CH1.setFont(font)
        self.Select_CH1.setObjectName("Select_CH1")
        self.verticalLayout_3.addWidget(self.Select_CH1, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.groupBox_18, 2, 2, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.AMCFirmware = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.AMCFirmware.setFont(font)
        self.AMCFirmware.setObjectName("AMCFirmware")
        self.verticalLayout_12.addWidget(self.AMCFirmware, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.groupBox_15, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.ROCFirmware = QtWidgets.QLabel(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ROCFirmware.setFont(font)
        self.ROCFirmware.setObjectName("ROCFirmware")
        self.verticalLayout_13.addWidget(self.ROCFirmware, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.groupBox_16, 3, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LinkNumber = QtWidgets.QSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LinkNumber.setFont(font)
        self.LinkNumber.setMaximum(16)
        self.LinkNumber.setObjectName("LinkNumber")
        self.verticalLayout.addWidget(self.LinkNumber)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LinkType = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LinkType.setFont(font)
        self.LinkType.setObjectName("LinkType")
        self.verticalLayout_2.addWidget(self.LinkType)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SerialNumber = QtWidgets.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SerialNumber.setFont(font)
        self.SerialNumber.setObjectName("SerialNumber")
        self.verticalLayout_4.addWidget(self.SerialNumber, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.groupBox_13, 2, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ModelName = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ModelName.setFont(font)
        self.ModelName.setObjectName("ModelName")
        self.verticalLayout_8.addWidget(self.ModelName, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.License = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.License.setFont(font)
        self.License.setObjectName("License")
        self.verticalLayout_14.addWidget(self.License, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.groupBox_17, 3, 2, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_14.setStyleSheet("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Disconn = QtWidgets.QRadioButton(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Disconn.setFont(font)
        self.Disconn.setAutoFillBackground(False)
        self.Disconn.setStyleSheet("QRadioButton::checked {color: green}")
        self.Disconn.setObjectName("Disconn")
        self.gridLayout_3.addWidget(self.Disconn, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Connect = QtWidgets.QRadioButton(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Connect.setFont(font)
        self.Connect.setAutoFillBackground(False)
        self.Connect.setStyleSheet("QRadioButton::checked {color: red}")
        self.Connect.setObjectName("Connect")
        self.gridLayout_3.addWidget(self.Connect, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.groupBox_14, 0, 2, 1, 1)
        self.Tabs.addTab(self.tab_CF, "")
        self.tab_HV = QtWidgets.QWidget()
        self.tab_HV.setEnabled(True)
        self.tab_HV.setStyleSheet("QLCDNumber {color: yellow;background-color: darkblue;}\n"
"QLabel {padding: 20px; font-size: 20pt; color: darkblue; font-weight:bold; }\n"
"QRadioButton {text-align: center; font-size: 24pt; font-weight:bold;}\n"
"QRadioButton::indicator { width: 36px; height: 36px; margin:1px; }\n"
"QSpinBox {font-size: 16pt;}\n"
"QGroupBox{border-width: 2px; font-size: 12pt;}")
        self.tab_HV.setObjectName("tab_HV")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_HV)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox.setStyleSheet("QGroupBox{background-color:black; border-radius: 1px; color:yellow; border: 0px ;  margin-top: 1 1ex;}\n"
"\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.VAct = QtWidgets.QLCDNumber(self.groupBox)
        self.VAct.setMinimumSize(QtCore.QSize(300, 80))
        self.VAct.setMaximumSize(QtCore.QSize(400, 80))
        self.VAct.setStyleSheet("QLCDNumber{color: yellow; background-color:black;}")
        self.VAct.setDigitCount(7)
        self.VAct.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.VAct.setObjectName("VAct")
        self.horizontalLayout_3.addWidget(self.VAct)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(46)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {color:yellow; font-size: 46pt; font-weight:normal;}")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.Title_0 = QtWidgets.QLabel(self.tab_HV)
        self.Title_0.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_0.setObjectName("Title_0")
        self.gridLayout_2.addWidget(self.Title_0, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.VMax = QtWidgets.QSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.VMax.setFont(font)
        self.VMax.setMaximum(1)
        self.VMax.setObjectName("VMax")
        self.verticalLayout_5.addWidget(self.VMax)
        self.gridLayout_2.addWidget(self.groupBox_7, 4, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.V_ON = QtWidgets.QRadioButton(self.groupBox_5)
        self.V_ON.setStyleSheet("QRadioButton::checked {color: red;}")
        self.V_ON.setObjectName("V_ON")
        self.horizontalLayout_4.addWidget(self.V_ON)
        self.V_OFF = QtWidgets.QRadioButton(self.groupBox_5)
        self.V_OFF.setStyleSheet("QRadioButton::checked {color: green}")
        self.V_OFF.setObjectName("V_OFF")
        self.horizontalLayout_4.addWidget(self.V_OFF)
        self.gridLayout_2.addWidget(self.groupBox_5, 3, 2, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.IMax = QtWidgets.QSpinBox(self.groupBox_9)
        self.IMax.setObjectName("IMax")
        self.verticalLayout_7.addWidget(self.IMax)
        self.gridLayout_2.addWidget(self.groupBox_9, 4, 2, 1, 1)
        self.Title_1 = QtWidgets.QLabel(self.tab_HV)
        self.Title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_1.setObjectName("Title_1")
        self.gridLayout_2.addWidget(self.Title_1, 0, 2, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.VSet = QtWidgets.QSpinBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.VSet.setFont(font)
        self.VSet.setMaximum(1)
        self.VSet.setObjectName("VSet")
        self.verticalLayout_10.addWidget(self.VSet)
        self.gridLayout_2.addWidget(self.groupBox_12, 3, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.RampUp = QtWidgets.QSpinBox(self.groupBox_8)
        self.RampUp.setObjectName("RampUp")
        self.verticalLayout_6.addWidget(self.RampUp)
        self.gridLayout_2.addWidget(self.groupBox_8, 5, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.RampDown = QtWidgets.QSpinBox(self.groupBox_11)
        self.RampDown.setObjectName("RampDown")
        self.verticalLayout_9.addWidget(self.RampDown)
        self.gridLayout_2.addWidget(self.groupBox_11, 5, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"background-color:black; \n"
"border-radius: 1px; \n"
"color:yellow; \n"
"border: 0px ;   \n"
"margin-top: 1 1ex;}\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.IAct = QtWidgets.QLCDNumber(self.groupBox_3)
        self.IAct.setMinimumSize(QtCore.QSize(300, 80))
        self.IAct.setMaximumSize(QtCore.QSize(400, 80))
        self.IAct.setStyleSheet("QLCDNumber{color: yellow; background-color:black;}")
        self.IAct.setDigitCount(6)
        self.IAct.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.IAct.setObjectName("IAct")
        self.horizontalLayout_7.addWidget(self.IAct)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setStyleSheet("QLabel {color:yellow; font-size: 46pt; font-weight:normal;}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 2, 1, 1)
        self.Tabs.addTab(self.tab_HV, "")
        self.tab_OS = QtWidgets.QWidget()
        self.tab_OS.setObjectName("tab_OS")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_OS)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.TopOSFrame = QtWidgets.QFrame(self.tab_OS)
        self.TopOSFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TopOSFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopOSFrame.setObjectName("TopOSFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.TopOSFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.QScope = OscCanvas(self.TopOSFrame)
        self.QScope.setObjectName("QScope")
        self.horizontalLayout.addWidget(self.QScope)
        self.RightFrame = QtWidgets.QFrame(self.TopOSFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RightFrame.sizePolicy().hasHeightForWidth())
        self.RightFrame.setSizePolicy(sizePolicy)
        self.RightFrame.setMinimumSize(QtCore.QSize(250, 0))
        self.RightFrame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.RightFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RightFrame.setLineWidth(0)
        self.RightFrame.setObjectName("RightFrame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.RightFrame)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_10 = QtWidgets.QGroupBox(self.RightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_16.setContentsMargins(2, 6, 2, 2)
        self.verticalLayout_16.setSpacing(4)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.InputRange = QtWidgets.QComboBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.InputRange.setFont(font)
        self.InputRange.setObjectName("InputRange")
        self.verticalLayout_16.addWidget(self.InputRange)
        self.InputPolarity = QtWidgets.QComboBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.InputPolarity.setFont(font)
        self.InputPolarity.setObjectName("InputPolarity")
        self.verticalLayout_16.addWidget(self.InputPolarity)
        self.DCoffsetSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.DCoffsetSpinBox.setFont(font)
        self.DCoffsetSpinBox.setDecimals(1)
        self.DCoffsetSpinBox.setMinimum(-50.0)
        self.DCoffsetSpinBox.setMaximum(50.0)
        self.DCoffsetSpinBox.setSingleStep(0.1)
        self.DCoffsetSpinBox.setObjectName("DCoffsetSpinBox")
        self.verticalLayout_16.addWidget(self.DCoffsetSpinBox)
        self.FineGainSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.FineGainSpinBox.setFont(font)
        self.FineGainSpinBox.setDecimals(4)
        self.FineGainSpinBox.setMinimum(0.5)
        self.FineGainSpinBox.setMaximum(1.5)
        self.FineGainSpinBox.setSingleStep(0.001)
        self.FineGainSpinBox.setProperty("value", 1.0)
        self.FineGainSpinBox.setObjectName("FineGainSpinBox")
        self.verticalLayout_16.addWidget(self.FineGainSpinBox)
        self.verticalLayout_18.addWidget(self.groupBox_10)
        self.groupBox_19 = QtWidgets.QGroupBox(self.RightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_19.sizePolicy().hasHeightForWidth())
        self.groupBox_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_17.setContentsMargins(2, 6, 2, 2)
        self.verticalLayout_17.setSpacing(4)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.Virtual_1 = QtWidgets.QComboBox(self.groupBox_19)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Virtual_1.setFont(font)
        self.Virtual_1.setObjectName("Virtual_1")
        self.verticalLayout_17.addWidget(self.Virtual_1)
        self.Virtual_2 = QtWidgets.QComboBox(self.groupBox_19)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Virtual_2.setFont(font)
        self.Virtual_2.setObjectName("Virtual_2")
        self.verticalLayout_17.addWidget(self.Virtual_2)
        self.Digital_1 = QtWidgets.QComboBox(self.groupBox_19)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Digital_1.setFont(font)
        self.Digital_1.setObjectName("Digital_1")
        self.verticalLayout_17.addWidget(self.Digital_1)
        self.verticalLayout_18.addWidget(self.groupBox_19)
        self.groupBox_23 = QtWidgets.QGroupBox(self.RightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_23.sizePolicy().hasHeightForWidth())
        self.groupBox_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_23.setFont(font)
        self.groupBox_23.setObjectName("groupBox_23")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_23)
        self.verticalLayout_11.setContentsMargins(2, 6, 2, 2)
        self.verticalLayout_11.setSpacing(4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.RiseTimeSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.RiseTimeSpinBox.setFont(font)
        self.RiseTimeSpinBox.setObjectName("RiseTimeSpinBox")
        self.verticalLayout_11.addWidget(self.RiseTimeSpinBox)
        self.DecayTimeSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.DecayTimeSpinBox.setFont(font)
        self.DecayTimeSpinBox.setObjectName("DecayTimeSpinBox")
        self.verticalLayout_11.addWidget(self.DecayTimeSpinBox)
        self.FlatTopSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.FlatTopSpinBox.setFont(font)
        self.FlatTopSpinBox.setObjectName("FlatTopSpinBox")
        self.verticalLayout_11.addWidget(self.FlatTopSpinBox)
        self.PeakDelaySpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.PeakDelaySpinBox.setFont(font)
        self.PeakDelaySpinBox.setObjectName("PeakDelaySpinBox")
        self.verticalLayout_11.addWidget(self.PeakDelaySpinBox)
        self.PeakMeanSpinBox = QtWidgets.QSpinBox(self.groupBox_23)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.PeakMeanSpinBox.setFont(font)
        self.PeakMeanSpinBox.setObjectName("PeakMeanSpinBox")
        self.verticalLayout_11.addWidget(self.PeakMeanSpinBox)
        self.PeakHoldoffSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.PeakHoldoffSpinBox.setFont(font)
        self.PeakHoldoffSpinBox.setObjectName("PeakHoldoffSpinBox")
        self.verticalLayout_11.addWidget(self.PeakHoldoffSpinBox)
        self.BaseMeanSpinBox = QtWidgets.QSpinBox(self.groupBox_23)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.BaseMeanSpinBox.setFont(font)
        self.BaseMeanSpinBox.setObjectName("BaseMeanSpinBox")
        self.verticalLayout_11.addWidget(self.BaseMeanSpinBox)
        self.BaseHoldoffSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.BaseHoldoffSpinBox.setFont(font)
        self.BaseHoldoffSpinBox.setObjectName("BaseHoldoffSpinBox")
        self.verticalLayout_11.addWidget(self.BaseHoldoffSpinBox)
        self.verticalLayout_18.addWidget(self.groupBox_23)
        self.horizontalLayout.addWidget(self.RightFrame)
        self.verticalLayout_15.addWidget(self.TopOSFrame)
        self.BottomOSFrame = QtWidgets.QFrame(self.tab_OS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BottomOSFrame.sizePolicy().hasHeightForWidth())
        self.BottomOSFrame.setSizePolicy(sizePolicy)
        self.BottomOSFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BottomOSFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomOSFrame.setObjectName("BottomOSFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.BottomOSFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_21 = QtWidgets.QGroupBox(self.BottomOSFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_21.sizePolicy().hasHeightForWidth())
        self.groupBox_21.setSizePolicy(sizePolicy)
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_5.setContentsMargins(0, 6, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Offset = QtWidgets.QDial(self.groupBox_21)
        self.Offset.setMinimum(-100)
        self.Offset.setMaximum(100)
        self.Offset.setObjectName("Offset")
        self.gridLayout_5.addWidget(self.Offset, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_21)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.VScale = QtWidgets.QDial(self.groupBox_21)
        self.VScale.setMaximum(8)
        self.VScale.setPageStep(2)
        self.VScale.setProperty("value", 4)
        self.VScale.setObjectName("VScale")
        self.gridLayout_5.addWidget(self.VScale, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.horizontalLayout_5.addWidget(self.groupBox_21)
        self.groupBox_25 = QtWidgets.QGroupBox(self.BottomOSFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_25.sizePolicy().hasHeightForWidth())
        self.groupBox_25.setSizePolicy(sizePolicy)
        self.groupBox_25.setObjectName("groupBox_25")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_25)
        self.gridLayout_8.setContentsMargins(0, 6, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.dial_2 = QtWidgets.QDial(self.groupBox_25)
        self.dial_2.setObjectName("dial_2")
        self.gridLayout_8.addWidget(self.dial_2, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.dial = QtWidgets.QDial(self.groupBox_25)
        self.dial.setObjectName("dial")
        self.gridLayout_8.addWidget(self.dial, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_25)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_5.addWidget(self.groupBox_25)
        self.groupBox_22 = QtWidgets.QGroupBox(self.BottomOSFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_22.sizePolicy().hasHeightForWidth())
        self.groupBox_22.setSizePolicy(sizePolicy)
        self.groupBox_22.setObjectName("groupBox_22")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_22)
        self.gridLayout_6.setContentsMargins(0, 6, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.HScale = QtWidgets.QDial(self.groupBox_22)
        self.HScale.setMaximum(8)
        self.HScale.setPageStep(2)
        self.HScale.setProperty("value", 4)
        self.HScale.setObjectName("HScale")
        self.gridLayout_6.addWidget(self.HScale, 1, 0, 1, 1)
        self.Delay = QtWidgets.QDial(self.groupBox_22)
        self.Delay.setMinimum(-100)
        self.Delay.setMaximum(100)
        self.Delay.setObjectName("Delay")
        self.gridLayout_6.addWidget(self.Delay, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_22)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_6 = QtWidgets.QLabel(self.groupBox_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.horizontalLayout_5.addWidget(self.groupBox_22)
        self.groupBox_20 = QtWidgets.QGroupBox(self.BottomOSFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_20.sizePolicy().hasHeightForWidth())
        self.groupBox_20.setSizePolicy(sizePolicy)
        self.groupBox_20.setMinimumSize(QtCore.QSize(440, 0))
        self.groupBox_20.setObjectName("groupBox_20")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_2.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TriggerFrame1 = QtWidgets.QFrame(self.groupBox_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerFrame1.sizePolicy().hasHeightForWidth())
        self.TriggerFrame1.setSizePolicy(sizePolicy)
        self.TriggerFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TriggerFrame1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TriggerFrame1.setObjectName("TriggerFrame1")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.TriggerFrame1)
        self.verticalLayout_20.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_20.setSpacing(2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.TriggerNormal = QtWidgets.QRadioButton(self.TriggerFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerNormal.sizePolicy().hasHeightForWidth())
        self.TriggerNormal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.TriggerNormal.setFont(font)
        self.TriggerNormal.setObjectName("TriggerNormal")
        self.verticalLayout_20.addWidget(self.TriggerNormal)
        self.TriggerExternal = QtWidgets.QRadioButton(self.TriggerFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerExternal.sizePolicy().hasHeightForWidth())
        self.TriggerExternal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.TriggerExternal.setFont(font)
        self.TriggerExternal.setObjectName("TriggerExternal")
        self.verticalLayout_20.addWidget(self.TriggerExternal)
        self.TriggerAuto = QtWidgets.QRadioButton(self.TriggerFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerAuto.sizePolicy().hasHeightForWidth())
        self.TriggerAuto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.TriggerAuto.setFont(font)
        self.TriggerAuto.setObjectName("TriggerAuto")
        self.verticalLayout_20.addWidget(self.TriggerAuto)
        self.TriggerButton = QtWidgets.QPushButton(self.TriggerFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerButton.sizePolicy().hasHeightForWidth())
        self.TriggerButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.TriggerButton.setFont(font)
        self.TriggerButton.setObjectName("TriggerButton")
        self.verticalLayout_20.addWidget(self.TriggerButton)
        self.horizontalLayout_2.addWidget(self.TriggerFrame1)
        self.TriggerFrame2 = QtWidgets.QFrame(self.groupBox_20)
        self.TriggerFrame2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TriggerFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TriggerFrame2.setObjectName("TriggerFrame2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.TriggerFrame2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.TriggerLevel = QtWidgets.QDial(self.TriggerFrame2)
        self.TriggerLevel.setMinimum(5)
        self.TriggerLevel.setMaximum(10000)
        self.TriggerLevel.setObjectName("TriggerLevel")
        self.verticalLayout_19.addWidget(self.TriggerLevel)
        self.TriggerSingle = QtWidgets.QCheckBox(self.TriggerFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerSingle.sizePolicy().hasHeightForWidth())
        self.TriggerSingle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.TriggerSingle.setFont(font)
        self.TriggerSingle.setObjectName("TriggerSingle")
        self.verticalLayout_19.addWidget(self.TriggerSingle)
        self.horizontalLayout_2.addWidget(self.TriggerFrame2)
        self.TriggerFrame3 = QtWidgets.QFrame(self.groupBox_20)
        self.TriggerFrame3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TriggerFrame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TriggerFrame3.setObjectName("TriggerFrame3")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.TriggerFrame3)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.TriggerRiseTime = QtWidgets.QDoubleSpinBox(self.TriggerFrame3)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.TriggerRiseTime.setFont(font)
        self.TriggerRiseTime.setSingleStep(0.1)
        self.TriggerRiseTime.setObjectName("TriggerRiseTime")
        self.verticalLayout_21.addWidget(self.TriggerRiseTime)
        self.TriggerHoldoff = QtWidgets.QDoubleSpinBox(self.TriggerFrame3)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.TriggerHoldoff.setFont(font)
        self.TriggerHoldoff.setDecimals(2)
        self.TriggerHoldoff.setMaximum(10.0)
        self.TriggerHoldoff.setSingleStep(0.1)
        self.TriggerHoldoff.setObjectName("TriggerHoldoff")
        self.verticalLayout_21.addWidget(self.TriggerHoldoff)
        self.TriggerPrologue = QtWidgets.QDoubleSpinBox(self.TriggerFrame3)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.TriggerPrologue.setFont(font)
        self.TriggerPrologue.setDecimals(2)
        self.TriggerPrologue.setMaximum(20.0)
        self.TriggerPrologue.setSingleStep(0.1)
        self.TriggerPrologue.setObjectName("TriggerPrologue")
        self.verticalLayout_21.addWidget(self.TriggerPrologue)
        self.TriggerSmoothing = QtWidgets.QSpinBox(self.TriggerFrame3)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.TriggerSmoothing.setFont(font)
        self.TriggerSmoothing.setSuffix("")
        self.TriggerSmoothing.setMinimum(4)
        self.TriggerSmoothing.setMaximum(16)
        self.TriggerSmoothing.setObjectName("TriggerSmoothing")
        self.verticalLayout_21.addWidget(self.TriggerSmoothing)
        self.horizontalLayout_2.addWidget(self.TriggerFrame3)
        self.horizontalLayout_5.addWidget(self.groupBox_20)
        self.verticalLayout_15.addWidget(self.BottomOSFrame)
        self.Tabs.addTab(self.tab_OS, "")
        self.tab_SP = QtWidgets.QWidget()
        self.tab_SP.setObjectName("tab_SP")
        self.Tabs.addTab(self.tab_SP, "")
        self.gridLayout.addWidget(self.Tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setEnabled(True)
        self.actionExit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Channel select"))
        self.Select_CH0.setText(_translate("MainWindow", "CHANNEL 0"))
        self.Select_CH1.setText(_translate("MainWindow", "CHANNEL 1"))
        self.groupBox_15.setTitle(_translate("MainWindow", "AMC Firmware"))
        self.AMCFirmware.setText(_translate("MainWindow", "----"))
        self.groupBox_16.setTitle(_translate("MainWindow", "ROC Firmware"))
        self.ROCFirmware.setText(_translate("MainWindow", "----"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Link number"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Connection type"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Serial Number"))
        self.SerialNumber.setText(_translate("MainWindow", "----"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Model Name"))
        self.ModelName.setText(_translate("MainWindow", "----"))
        self.groupBox_17.setTitle(_translate("MainWindow", "License"))
        self.License.setText(_translate("MainWindow", "----"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Control connection"))
        self.Disconn.setText(_translate("MainWindow", "Disconnected"))
        self.Connect.setText(_translate("MainWindow", "Connect"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_CF), _translate("MainWindow", "Connection"))
        self.groupBox.setTitle(_translate("MainWindow", " Actual Voltage"))
        self.label.setText(_translate("MainWindow", "V"))
        self.Title_0.setText(_translate("MainWindow", "title1"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Limit Maximum Voltage to"))
        self.VMax.setSuffix(_translate("MainWindow", " V"))
        self.groupBox_5.setTitle(_translate("MainWindow", "CONTROL"))
        self.V_ON.setText(_translate("MainWindow", "ON"))
        self.V_OFF.setText(_translate("MainWindow", "OFF"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Limit Maximum Current to"))
        self.IMax.setSuffix(_translate("MainWindow", " μA"))
        self.Title_1.setText(_translate("MainWindow", "title2"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Set Voltage"))
        self.VSet.setSuffix(_translate("MainWindow", " V"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Set Ramp Up Speed to"))
        self.RampUp.setSuffix(_translate("MainWindow", " V/s"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Set Ramp Down Speed to"))
        self.RampDown.setSuffix(_translate("MainWindow", " V/s"))
        self.groupBox_3.setTitle(_translate("MainWindow", " Actual Current"))
        self.label_2.setText(_translate("MainWindow", "μA"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_HV), _translate("MainWindow", "High Voltage"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Analog Input"))
        self.DCoffsetSpinBox.setPrefix(_translate("MainWindow", "DC Offset:  "))
        self.DCoffsetSpinBox.setSuffix(_translate("MainWindow", " %"))
        self.FineGainSpinBox.setPrefix(_translate("MainWindow", "Fine gain: "))
        self.groupBox_19.setTitle(_translate("MainWindow", "Traces A, B, C"))
        self.groupBox_23.setTitle(_translate("MainWindow", "Digital Shaper"))
        self.RiseTimeSpinBox.setPrefix(_translate("MainWindow", "Rise Time:    "))
        self.RiseTimeSpinBox.setSuffix(_translate("MainWindow", " μs"))
        self.DecayTimeSpinBox.setPrefix(_translate("MainWindow", "Decay Time:   "))
        self.DecayTimeSpinBox.setSuffix(_translate("MainWindow", " μs"))
        self.FlatTopSpinBox.setPrefix(_translate("MainWindow", "Flat Top:     "))
        self.FlatTopSpinBox.setSuffix(_translate("MainWindow", " μs"))
        self.PeakDelaySpinBox.setPrefix(_translate("MainWindow", "Peak Delay:   "))
        self.PeakDelaySpinBox.setSuffix(_translate("MainWindow", " μs"))
        self.PeakMeanSpinBox.setSuffix(_translate("MainWindow", " samples"))
        self.PeakMeanSpinBox.setPrefix(_translate("MainWindow", "Peak Mean:    "))
        self.PeakHoldoffSpinBox.setPrefix(_translate("MainWindow", "Peak Holdoff: "))
        self.PeakHoldoffSpinBox.setSuffix(_translate("MainWindow", " μs"))
        self.BaseMeanSpinBox.setSuffix(_translate("MainWindow", " samples"))
        self.BaseMeanSpinBox.setPrefix(_translate("MainWindow", "Base Mean:    "))
        self.BaseHoldoffSpinBox.setPrefix(_translate("MainWindow", "Base Holdoff: "))
        self.BaseHoldoffSpinBox.setSuffix(_translate("MainWindow", " μs"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Vertical A"))
        self.label_3.setText(_translate("MainWindow", "Scale"))
        self.label_4.setText(_translate("MainWindow", "Offset"))
        self.groupBox_25.setTitle(_translate("MainWindow", "Vertical B"))
        self.label_8.setText(_translate("MainWindow", "Offset"))
        self.label_7.setText(_translate("MainWindow", "Scale"))
        self.groupBox_22.setTitle(_translate("MainWindow", "Horizontal"))
        self.label_5.setText(_translate("MainWindow", "Scale"))
        self.label_6.setText(_translate("MainWindow", "Offset"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Trigger"))
        self.TriggerNormal.setText(_translate("MainWindow", "Normal"))
        self.TriggerExternal.setText(_translate("MainWindow", "External"))
        self.TriggerAuto.setText(_translate("MainWindow", "Auto"))
        self.TriggerButton.setText(_translate("MainWindow", "Start"))
        self.TriggerSingle.setText(_translate("MainWindow", "Single"))
        self.TriggerRiseTime.setPrefix(_translate("MainWindow", "Rise Time: "))
        self.TriggerRiseTime.setSuffix(_translate("MainWindow", " μs"))
        self.TriggerHoldoff.setPrefix(_translate("MainWindow", "Holdoff:   "))
        self.TriggerHoldoff.setSuffix(_translate("MainWindow", " μs"))
        self.TriggerPrologue.setPrefix(_translate("MainWindow", "Preamble:  "))
        self.TriggerPrologue.setSuffix(_translate("MainWindow", " μs"))
        self.TriggerSmoothing.setPrefix(_translate("MainWindow", "Smoothing: "))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_OS), _translate("MainWindow", "Oscilloscope"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_SP), _translate("MainWindow", "Spectrum"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit Application"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

from TABs.Scope import OscCanvas
