# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1140, 891)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Tabs.setFont(font)
        self.Tabs.setAutoFillBackground(True)
        self.Tabs.setStyleSheet("QGroupBox { border: 1px solid grey;   border-radius: 10px;   font-weight: bold; font-size: 12pt; color: black; padding:8px; margin:8px; background-color: #F0F0F0;}\n"
"QGroupBox::title {  subcontrol-origin: margin;   subcontrol-position: top center;    padding:  0 5px;  }\n"
"QSpinBox {             background-color: #FFFFFF; }\n"
"QDoubleSpinBox {background-color: #FFFFFF;} \n"
"")
        self.Tabs.setObjectName("Tabs")
        self.tab_CF = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_CF.setFont(font)
        self.tab_CF.setObjectName("tab_CF")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_CF)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.InputComboBox = QtWidgets.QComboBox(self.groupBox_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputComboBox.sizePolicy().hasHeightForWidth())
        self.InputComboBox.setSizePolicy(sizePolicy)
        self.InputComboBox.setObjectName("InputComboBox")
        self.verticalLayout_3.addWidget(self.InputComboBox)
        self.HVComboBox = QtWidgets.QComboBox(self.groupBox_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HVComboBox.sizePolicy().hasHeightForWidth())
        self.HVComboBox.setSizePolicy(sizePolicy)
        self.HVComboBox.setObjectName("HVComboBox")
        self.verticalLayout_3.addWidget(self.HVComboBox)
        self.gridLayout_4.addWidget(self.groupBox_18, 2, 2, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ROCFirmware = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.ROCFirmware.setFont(font)
        self.ROCFirmware.setObjectName("ROCFirmware")
        self.verticalLayout_8.addWidget(self.ROCFirmware, 0, QtCore.Qt.AlignHCenter)
        self.AMCFirmware = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.AMCFirmware.setFont(font)
        self.AMCFirmware.setObjectName("AMCFirmware")
        self.verticalLayout_8.addWidget(self.AMCFirmware, 0, QtCore.Qt.AlignHCenter)
        self.License = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.License.setFont(font)
        self.License.setObjectName("License")
        self.verticalLayout_8.addWidget(self.License, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.groupBox_15, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout_4.addWidget(self.groupBox_16, 3, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LinkNumber = QtWidgets.QSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LinkNumber.setFont(font)
        self.LinkNumber.setMaximum(16)
        self.LinkNumber.setObjectName("LinkNumber")
        self.verticalLayout.addWidget(self.LinkNumber)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LinkType = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LinkType.setFont(font)
        self.LinkType.setObjectName("LinkType")
        self.verticalLayout_2.addWidget(self.LinkType)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_CF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Channels = QtWidgets.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Channels.setFont(font)
        self.Channels.setObjectName("Channels")
        self.verticalLayout_12.addWidget(self.Channels, 0, QtCore.Qt.AlignHCenter)
        self.HVChannels = QtWidgets.QLabel(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HVChannels.sizePolicy().hasHeightForWidth())
        self.HVChannels.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HVChannels.setFont(font)
        self.HVChannels.setObjectName("HVChannels")
        self.verticalLayout_12.addWidget(self.HVChannels, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.groupBox_13, 2, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.SerialNumber = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.SerialNumber.setFont(font)
        self.SerialNumber.setObjectName("SerialNumber")
        self.gridLayout_11.addWidget(self.SerialNumber, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.ModelName = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ModelName.setFont(font)
        self.ModelName.setObjectName("ModelName")
        self.gridLayout_11.addWidget(self.ModelName, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.FamilyCode = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FamilyCode.setFont(font)
        self.FamilyCode.setObjectName("FamilyCode")
        self.gridLayout_11.addWidget(self.FamilyCode, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.gridLayout_4.addWidget(self.groupBox_17, 3, 2, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_CF)
        self.groupBox_14.setStyleSheet("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Disconn = QtWidgets.QRadioButton(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Disconn.setFont(font)
        self.Disconn.setAutoFillBackground(False)
        self.Disconn.setStyleSheet("QRadioButton::checked {color: green}")
        self.Disconn.setObjectName("Disconn")
        self.gridLayout_3.addWidget(self.Disconn, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Connect = QtWidgets.QRadioButton(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Connect.setFont(font)
        self.Connect.setAutoFillBackground(False)
        self.Connect.setStyleSheet("QRadioButton::checked {color: red}")
        self.Connect.setObjectName("Connect")
        self.gridLayout_3.addWidget(self.Connect, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.groupBox_14, 0, 2, 1, 1)
        self.Tabs.addTab(self.tab_CF, "")
        self.tab_HV = QtWidgets.QWidget()
        self.tab_HV.setEnabled(True)
        self.tab_HV.setStyleSheet("QLCDNumber {color: yellow;background-color: darkblue;}\n"
"QLabel {padding: 20px; font-size: 20pt; color: darkblue; font-weight:bold; }\n"
"QRadioButton {text-align: center; font-size: 24pt; font-weight:bold;}\n"
"QRadioButton::indicator { width: 36px; height: 36px; margin:1px; }\n"
"QSpinBox {font-size: 16pt;}\n"
"QGroupBox{border-width: 2px; font-size: 12pt;}")
        self.tab_HV.setObjectName("tab_HV")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_HV)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox.setStyleSheet("QGroupBox{background-color:black; border-radius: 1px; color:yellow; border: 0px ;  margin-top: 1 1ex;}\n"
"\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.VAct = QtWidgets.QLCDNumber(self.groupBox)
        self.VAct.setMinimumSize(QtCore.QSize(300, 80))
        self.VAct.setMaximumSize(QtCore.QSize(400, 80))
        self.VAct.setStyleSheet("QLCDNumber{color: yellow; background-color:black;}")
        self.VAct.setDigitCount(7)
        self.VAct.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.VAct.setObjectName("VAct")
        self.horizontalLayout_3.addWidget(self.VAct)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(46)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {color:yellow; font-size: 46pt; font-weight:normal;}")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.Title_0 = QtWidgets.QLabel(self.tab_HV)
        self.Title_0.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_0.setObjectName("Title_0")
        self.gridLayout_2.addWidget(self.Title_0, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.VMax = QtWidgets.QSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.VMax.setFont(font)
        self.VMax.setMaximum(1)
        self.VMax.setObjectName("VMax")
        self.verticalLayout_5.addWidget(self.VMax)
        self.gridLayout_2.addWidget(self.groupBox_7, 4, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.V_ON = QtWidgets.QRadioButton(self.groupBox_5)
        self.V_ON.setStyleSheet("QRadioButton::checked {color: red;}")
        self.V_ON.setObjectName("V_ON")
        self.horizontalLayout_4.addWidget(self.V_ON)
        self.V_OFF = QtWidgets.QRadioButton(self.groupBox_5)
        self.V_OFF.setStyleSheet("QRadioButton::checked {color: green}")
        self.V_OFF.setObjectName("V_OFF")
        self.horizontalLayout_4.addWidget(self.V_OFF)
        self.gridLayout_2.addWidget(self.groupBox_5, 3, 2, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.IMax = QtWidgets.QSpinBox(self.groupBox_9)
        self.IMax.setObjectName("IMax")
        self.verticalLayout_7.addWidget(self.IMax)
        self.gridLayout_2.addWidget(self.groupBox_9, 4, 2, 1, 1)
        self.Title_1 = QtWidgets.QLabel(self.tab_HV)
        self.Title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_1.setObjectName("Title_1")
        self.gridLayout_2.addWidget(self.Title_1, 0, 2, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.VSet = QtWidgets.QSpinBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.VSet.setFont(font)
        self.VSet.setMaximum(1)
        self.VSet.setObjectName("VSet")
        self.verticalLayout_10.addWidget(self.VSet)
        self.gridLayout_2.addWidget(self.groupBox_12, 3, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.RampUp = QtWidgets.QSpinBox(self.groupBox_8)
        self.RampUp.setObjectName("RampUp")
        self.verticalLayout_6.addWidget(self.RampUp)
        self.gridLayout_2.addWidget(self.groupBox_8, 5, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.RampDown = QtWidgets.QSpinBox(self.groupBox_11)
        self.RampDown.setObjectName("RampDown")
        self.verticalLayout_9.addWidget(self.RampDown)
        self.gridLayout_2.addWidget(self.groupBox_11, 5, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_HV)
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"background-color:black; \n"
"border-radius: 1px; \n"
"color:yellow; \n"
"border: 0px ;   \n"
"margin-top: 1 1ex;}\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.IAct = QtWidgets.QLCDNumber(self.groupBox_3)
        self.IAct.setMinimumSize(QtCore.QSize(300, 80))
        self.IAct.setMaximumSize(QtCore.QSize(400, 80))
        self.IAct.setStyleSheet("QLCDNumber{color: yellow; background-color:black;}")
        self.IAct.setDigitCount(6)
        self.IAct.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.IAct.setObjectName("IAct")
        self.horizontalLayout_7.addWidget(self.IAct)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setStyleSheet("QLabel {color:yellow; font-size: 46pt; font-weight:normal;}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 2, 1, 1)
        self.Tabs.addTab(self.tab_HV, "")
        self.tab_OS = QtWidgets.QWidget()
        self.tab_OS.setObjectName("tab_OS")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_OS)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.TopOSFrame = QtWidgets.QFrame(self.tab_OS)
        self.TopOSFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TopOSFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopOSFrame.setLineWidth(2)
        self.TopOSFrame.setObjectName("TopOSFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.TopOSFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.TopOSFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_22.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.QScope = OscCanvas(self.frame)
        self.QScope.setObjectName("QScope")
        self.verticalLayout_22.addWidget(self.QScope)
        self.horizontalLayout.addWidget(self.frame)
        self.RightFrame = QtWidgets.QFrame(self.TopOSFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RightFrame.sizePolicy().hasHeightForWidth())
        self.RightFrame.setSizePolicy(sizePolicy)
        self.RightFrame.setMinimumSize(QtCore.QSize(250, 0))
        self.RightFrame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.RightFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RightFrame.setLineWidth(0)
        self.RightFrame.setObjectName("RightFrame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.RightFrame)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_10 = QtWidgets.QGroupBox(self.RightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_16.setContentsMargins(2, 6, 2, 2)
        self.verticalLayout_16.setSpacing(4)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.InputRange = QtWidgets.QComboBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.InputRange.setFont(font)
        self.InputRange.setObjectName("InputRange")
        self.verticalLayout_16.addWidget(self.InputRange)
        self.InputPolarity = QtWidgets.QComboBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.InputPolarity.setFont(font)
        self.InputPolarity.setObjectName("InputPolarity")
        self.verticalLayout_16.addWidget(self.InputPolarity)
        self.DCoffsetSpinBox = QtWidgets.QSpinBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DCoffsetSpinBox.sizePolicy().hasHeightForWidth())
        self.DCoffsetSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.DCoffsetSpinBox.setFont(font)
        self.DCoffsetSpinBox.setMaximum(100)
        self.DCoffsetSpinBox.setObjectName("DCoffsetSpinBox")
        self.verticalLayout_16.addWidget(self.DCoffsetSpinBox)
        self.FineGainSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FineGainSpinBox.sizePolicy().hasHeightForWidth())
        self.FineGainSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.FineGainSpinBox.setFont(font)
        self.FineGainSpinBox.setDecimals(4)
        self.FineGainSpinBox.setMinimum(0.5)
        self.FineGainSpinBox.setMaximum(5.0)
        self.FineGainSpinBox.setSingleStep(0.1)
        self.FineGainSpinBox.setProperty("value", 1.0)
        self.FineGainSpinBox.setObjectName("FineGainSpinBox")
        self.verticalLayout_16.addWidget(self.FineGainSpinBox)
        self.verticalLayout_18.addWidget(self.groupBox_10)
        self.groupBox_19 = QtWidgets.QGroupBox(self.RightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_19.sizePolicy().hasHeightForWidth())
        self.groupBox_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_17.setContentsMargins(2, 6, 2, 2)
        self.verticalLayout_17.setSpacing(4)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.Virtual_1 = QtWidgets.QComboBox(self.groupBox_19)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Virtual_1.setFont(font)
        self.Virtual_1.setObjectName("Virtual_1")
        self.verticalLayout_17.addWidget(self.Virtual_1)
        self.Virtual_2 = QtWidgets.QComboBox(self.groupBox_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Virtual_2.sizePolicy().hasHeightForWidth())
        self.Virtual_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Virtual_2.setFont(font)
        self.Virtual_2.setObjectName("Virtual_2")
        self.verticalLayout_17.addWidget(self.Virtual_2)
        self.Digital_1 = QtWidgets.QComboBox(self.groupBox_19)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Digital_1.setFont(font)
        self.Digital_1.setObjectName("Digital_1")
        self.verticalLayout_17.addWidget(self.Digital_1)
        self.verticalLayout_18.addWidget(self.groupBox_19)
        self.groupBox_23 = QtWidgets.QGroupBox(self.RightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_23.sizePolicy().hasHeightForWidth())
        self.groupBox_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_23.setFont(font)
        self.groupBox_23.setObjectName("groupBox_23")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_23)
        self.verticalLayout_11.setContentsMargins(2, 6, 2, 2)
        self.verticalLayout_11.setSpacing(4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.RiseTimeSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RiseTimeSpinBox.sizePolicy().hasHeightForWidth())
        self.RiseTimeSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.RiseTimeSpinBox.setFont(font)
        self.RiseTimeSpinBox.setDecimals(1)
        self.RiseTimeSpinBox.setMinimum(0.1)
        self.RiseTimeSpinBox.setSingleStep(0.1)
        self.RiseTimeSpinBox.setProperty("value", 1.0)
        self.RiseTimeSpinBox.setObjectName("RiseTimeSpinBox")
        self.verticalLayout_11.addWidget(self.RiseTimeSpinBox)
        self.DecayTimeSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DecayTimeSpinBox.sizePolicy().hasHeightForWidth())
        self.DecayTimeSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.DecayTimeSpinBox.setFont(font)
        self.DecayTimeSpinBox.setDecimals(1)
        self.DecayTimeSpinBox.setMinimum(0.1)
        self.DecayTimeSpinBox.setProperty("value", 50.0)
        self.DecayTimeSpinBox.setObjectName("DecayTimeSpinBox")
        self.verticalLayout_11.addWidget(self.DecayTimeSpinBox)
        self.FlatTopSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FlatTopSpinBox.sizePolicy().hasHeightForWidth())
        self.FlatTopSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.FlatTopSpinBox.setFont(font)
        self.FlatTopSpinBox.setDecimals(1)
        self.FlatTopSpinBox.setSingleStep(0.1)
        self.FlatTopSpinBox.setProperty("value", 1.0)
        self.FlatTopSpinBox.setObjectName("FlatTopSpinBox")
        self.verticalLayout_11.addWidget(self.FlatTopSpinBox)
        self.PeakDelaySpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PeakDelaySpinBox.sizePolicy().hasHeightForWidth())
        self.PeakDelaySpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.PeakDelaySpinBox.setFont(font)
        self.PeakDelaySpinBox.setDecimals(1)
        self.PeakDelaySpinBox.setSingleStep(0.1)
        self.PeakDelaySpinBox.setProperty("value", 1.0)
        self.PeakDelaySpinBox.setObjectName("PeakDelaySpinBox")
        self.verticalLayout_11.addWidget(self.PeakDelaySpinBox)
        self.PeakHoldoffSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PeakHoldoffSpinBox.sizePolicy().hasHeightForWidth())
        self.PeakHoldoffSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.PeakHoldoffSpinBox.setFont(font)
        self.PeakHoldoffSpinBox.setDecimals(1)
        self.PeakHoldoffSpinBox.setSingleStep(0.1)
        self.PeakHoldoffSpinBox.setProperty("value", 1.0)
        self.PeakHoldoffSpinBox.setObjectName("PeakHoldoffSpinBox")
        self.verticalLayout_11.addWidget(self.PeakHoldoffSpinBox)
        self.PeakMean = QtWidgets.QComboBox(self.groupBox_23)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.PeakMean.setFont(font)
        self.PeakMean.setObjectName("PeakMean")
        self.verticalLayout_11.addWidget(self.PeakMean)
        self.BaseMean = QtWidgets.QComboBox(self.groupBox_23)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.BaseMean.setFont(font)
        self.BaseMean.setObjectName("BaseMean")
        self.verticalLayout_11.addWidget(self.BaseMean)
        self.BaseHoldoffSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BaseHoldoffSpinBox.sizePolicy().hasHeightForWidth())
        self.BaseHoldoffSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.BaseHoldoffSpinBox.setFont(font)
        self.BaseHoldoffSpinBox.setDecimals(1)
        self.BaseHoldoffSpinBox.setSingleStep(0.1)
        self.BaseHoldoffSpinBox.setProperty("value", 1.0)
        self.BaseHoldoffSpinBox.setObjectName("BaseHoldoffSpinBox")
        self.verticalLayout_11.addWidget(self.BaseHoldoffSpinBox)
        self.verticalLayout_18.addWidget(self.groupBox_23)
        self.horizontalLayout.addWidget(self.RightFrame)
        self.verticalLayout_15.addWidget(self.TopOSFrame)
        self.BottomOSFrame = QtWidgets.QFrame(self.tab_OS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BottomOSFrame.sizePolicy().hasHeightForWidth())
        self.BottomOSFrame.setSizePolicy(sizePolicy)
        self.BottomOSFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BottomOSFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomOSFrame.setObjectName("BottomOSFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.BottomOSFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_21 = QtWidgets.QGroupBox(self.BottomOSFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_21.sizePolicy().hasHeightForWidth())
        self.groupBox_21.setSizePolicy(sizePolicy)
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ShiftA = QtWidgets.QDial(self.groupBox_21)
        self.ShiftA.setMinimum(-100)
        self.ShiftA.setMaximum(100)
        self.ShiftA.setObjectName("ShiftA")
        self.gridLayout_5.addWidget(self.ShiftA, 1, 1, 1, 1)
        self.ScaleA = QtWidgets.QDial(self.groupBox_21)
        self.ScaleA.setMaximum(8)
        self.ScaleA.setPageStep(2)
        self.ScaleA.setProperty("value", 4)
        self.ScaleA.setObjectName("ScaleA")
        self.gridLayout_5.addWidget(self.ScaleA, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_21)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.groupBox_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addWidget(self.groupBox_21)
        self.groupBox_25 = QtWidgets.QGroupBox(self.BottomOSFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_25.sizePolicy().hasHeightForWidth())
        self.groupBox_25.setSizePolicy(sizePolicy)
        self.groupBox_25.setObjectName("groupBox_25")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_25)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.ShiftB = QtWidgets.QDial(self.groupBox_25)
        self.ShiftB.setMinimum(-100)
        self.ShiftB.setMaximum(100)
        self.ShiftB.setObjectName("ShiftB")
        self.gridLayout_8.addWidget(self.ShiftB, 1, 1, 1, 1)
        self.ScaleB = QtWidgets.QDial(self.groupBox_25)
        self.ScaleB.setMaximum(8)
        self.ScaleB.setPageStep(2)
        self.ScaleB.setProperty("value", 4)
        self.ScaleB.setObjectName("ScaleB")
        self.gridLayout_8.addWidget(self.ScaleB, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_25)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.groupBox_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addWidget(self.groupBox_25)
        self.groupBox_22 = QtWidgets.QGroupBox(self.BottomOSFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_22.sizePolicy().hasHeightForWidth())
        self.groupBox_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_22.setFont(font)
        self.groupBox_22.setObjectName("groupBox_22")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_22)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ScaleT = QtWidgets.QDial(self.groupBox_22)
        self.ScaleT.setMaximum(8)
        self.ScaleT.setPageStep(2)
        self.ScaleT.setProperty("value", 4)
        self.ScaleT.setObjectName("ScaleT")
        self.gridLayout_6.addWidget(self.ScaleT, 1, 0, 1, 1)
        self.ShiftT = QtWidgets.QDial(self.groupBox_22)
        self.ShiftT.setMinimum(-100)
        self.ShiftT.setMaximum(100)
        self.ShiftT.setObjectName("ShiftT")
        self.gridLayout_6.addWidget(self.ShiftT, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_22)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.groupBox_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addWidget(self.groupBox_22)
        self.groupBox_20 = QtWidgets.QGroupBox(self.BottomOSFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_20.sizePolicy().hasHeightForWidth())
        self.groupBox_20.setSizePolicy(sizePolicy)
        self.groupBox_20.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBox_20.setObjectName("groupBox_20")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TriggerFrame2 = QtWidgets.QFrame(self.groupBox_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerFrame2.sizePolicy().hasHeightForWidth())
        self.TriggerFrame2.setSizePolicy(sizePolicy)
        self.TriggerFrame2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TriggerFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TriggerFrame2.setObjectName("TriggerFrame2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.TriggerFrame2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.TriggerLevel = QtWidgets.QDial(self.TriggerFrame2)
        self.TriggerLevel.setMinimum(0)
        self.TriggerLevel.setMaximum(16383)
        self.TriggerLevel.setSingleStep(4)
        self.TriggerLevel.setPageStep(16)
        self.TriggerLevel.setProperty("value", 0)
        self.TriggerLevel.setObjectName("TriggerLevel")
        self.verticalLayout_19.addWidget(self.TriggerLevel)
        self.TriggerButton = QtWidgets.QPushButton(self.TriggerFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerButton.sizePolicy().hasHeightForWidth())
        self.TriggerButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.TriggerButton.setFont(font)
        self.TriggerButton.setObjectName("TriggerButton")
        self.verticalLayout_19.addWidget(self.TriggerButton, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.TriggerFrame2)
        self.TriggerFrame3 = QtWidgets.QFrame(self.groupBox_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerFrame3.sizePolicy().hasHeightForWidth())
        self.TriggerFrame3.setSizePolicy(sizePolicy)
        self.TriggerFrame3.setMinimumSize(QtCore.QSize(220, 0))
        self.TriggerFrame3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TriggerFrame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TriggerFrame3.setObjectName("TriggerFrame3")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.TriggerFrame3)
        self.verticalLayout_21.setContentsMargins(0, 8, 0, 5)
        self.verticalLayout_21.setSpacing(5)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.TriggerMode = QtWidgets.QComboBox(self.TriggerFrame3)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.TriggerMode.setFont(font)
        self.TriggerMode.setObjectName("TriggerMode")
        self.verticalLayout_21.addWidget(self.TriggerMode)
        self.TriggerRiseTime = QtWidgets.QDoubleSpinBox(self.TriggerFrame3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerRiseTime.sizePolicy().hasHeightForWidth())
        self.TriggerRiseTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.TriggerRiseTime.setFont(font)
        self.TriggerRiseTime.setDecimals(1)
        self.TriggerRiseTime.setSingleStep(0.1)
        self.TriggerRiseTime.setProperty("value", 1.0)
        self.TriggerRiseTime.setObjectName("TriggerRiseTime")
        self.verticalLayout_21.addWidget(self.TriggerRiseTime)
        self.TriggerHoldoff = QtWidgets.QDoubleSpinBox(self.TriggerFrame3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerHoldoff.sizePolicy().hasHeightForWidth())
        self.TriggerHoldoff.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.TriggerHoldoff.setFont(font)
        self.TriggerHoldoff.setDecimals(1)
        self.TriggerHoldoff.setMaximum(10.0)
        self.TriggerHoldoff.setSingleStep(0.1)
        self.TriggerHoldoff.setProperty("value", 1.0)
        self.TriggerHoldoff.setObjectName("TriggerHoldoff")
        self.verticalLayout_21.addWidget(self.TriggerHoldoff)
        self.TriggerIntro = QtWidgets.QDoubleSpinBox(self.TriggerFrame3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TriggerIntro.sizePolicy().hasHeightForWidth())
        self.TriggerIntro.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.TriggerIntro.setFont(font)
        self.TriggerIntro.setDecimals(1)
        self.TriggerIntro.setMaximum(20.0)
        self.TriggerIntro.setSingleStep(0.1)
        self.TriggerIntro.setObjectName("TriggerIntro")
        self.verticalLayout_21.addWidget(self.TriggerIntro)
        self.Smoothin = QtWidgets.QComboBox(self.TriggerFrame3)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(9)
        self.Smoothin.setFont(font)
        self.Smoothin.setObjectName("Smoothin")
        self.verticalLayout_21.addWidget(self.Smoothin)
        self.horizontalLayout_2.addWidget(self.TriggerFrame3)
        self.horizontalLayout_5.addWidget(self.groupBox_20)
        self.verticalLayout_15.addWidget(self.BottomOSFrame)
        self.Tabs.addTab(self.tab_OS, "")
        self.tab_SP = QtWidgets.QWidget()
        self.tab_SP.setObjectName("tab_SP")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab_SP)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_8 = QtWidgets.QFrame(self.tab_SP)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setLineWidth(2)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.AcqWidget = AcqCanvas(self.frame_8)
        self.AcqWidget.setObjectName("AcqWidget")
        self.verticalLayout_25.addWidget(self.AcqWidget)
        self.verticalLayout_20.addWidget(self.frame_8)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_SP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ZoomComboBox = QtWidgets.QComboBox(self.page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZoomComboBox.sizePolicy().hasHeightForWidth())
        self.ZoomComboBox.setSizePolicy(sizePolicy)
        self.ZoomComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.ZoomComboBox.setObjectName("ZoomComboBox")
        self.horizontalLayout_9.addWidget(self.ZoomComboBox)
        self.HistogramScrollBar = QtWidgets.QScrollBar(self.page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HistogramScrollBar.sizePolicy().hasHeightForWidth())
        self.HistogramScrollBar.setSizePolicy(sizePolicy)
        self.HistogramScrollBar.setMinimumSize(QtCore.QSize(0, 20))
        self.HistogramScrollBar.setAutoFillBackground(False)
        self.HistogramScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.HistogramScrollBar.setInvertedAppearance(False)
        self.HistogramScrollBar.setInvertedControls(False)
        self.HistogramScrollBar.setObjectName("HistogramScrollBar")
        self.horizontalLayout_9.addWidget(self.HistogramScrollBar)
        self.LogScaleCheckBox = QtWidgets.QCheckBox(self.page_1)
        self.LogScaleCheckBox.setObjectName("LogScaleCheckBox")
        self.horizontalLayout_9.addWidget(self.LogScaleCheckBox)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.ACheckBox = QtWidgets.QCheckBox(self.page_2)
        self.ACheckBox.setObjectName("ACheckBox")
        self.horizontalLayout_13.addWidget(self.ACheckBox, 0, QtCore.Qt.AlignHCenter)
        self.BCheckBox = QtWidgets.QCheckBox(self.page_2)
        self.BCheckBox.setObjectName("BCheckBox")
        self.horizontalLayout_13.addWidget(self.BCheckBox, 0, QtCore.Qt.AlignHCenter)
        self.CCheckBox = QtWidgets.QCheckBox(self.page_2)
        self.CCheckBox.setObjectName("CCheckBox")
        self.horizontalLayout_13.addWidget(self.CCheckBox, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_20.addWidget(self.stackedWidget)
        self.tab_sp_bottom_frame = QtWidgets.QFrame(self.tab_SP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_sp_bottom_frame.sizePolicy().hasHeightForWidth())
        self.tab_sp_bottom_frame.setSizePolicy(sizePolicy)
        self.tab_sp_bottom_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tab_sp_bottom_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tab_sp_bottom_frame.setLineWidth(0)
        self.tab_sp_bottom_frame.setObjectName("tab_sp_bottom_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_sp_bottom_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.AcqControlGroupBox = QtWidgets.QGroupBox(self.tab_sp_bottom_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AcqControlGroupBox.sizePolicy().hasHeightForWidth())
        self.AcqControlGroupBox.setSizePolicy(sizePolicy)
        self.AcqControlGroupBox.setMinimumSize(QtCore.QSize(600, 0))
        self.AcqControlGroupBox.setObjectName("AcqControlGroupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.AcqControlGroupBox)
        self.gridLayout_7.setContentsMargins(1, 10, 1, 1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ClearAcqButton = QtWidgets.QPushButton(self.AcqControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearAcqButton.sizePolicy().hasHeightForWidth())
        self.ClearAcqButton.setSizePolicy(sizePolicy)
        self.ClearAcqButton.setObjectName("ClearAcqButton")
        self.gridLayout_7.addWidget(self.ClearAcqButton, 0, 3, 1, 1)
        self.ThresholdASpinBox = QtWidgets.QSpinBox(self.AcqControlGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ThresholdASpinBox.setFont(font)
        self.ThresholdASpinBox.setMaximum(16383)
        self.ThresholdASpinBox.setObjectName("ThresholdASpinBox")
        self.gridLayout_7.addWidget(self.ThresholdASpinBox, 6, 1, 1, 1)
        self.SaveAcqButton = QtWidgets.QPushButton(self.AcqControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveAcqButton.sizePolicy().hasHeightForWidth())
        self.SaveAcqButton.setSizePolicy(sizePolicy)
        self.SaveAcqButton.setObjectName("SaveAcqButton")
        self.gridLayout_7.addWidget(self.SaveAcqButton, 0, 4, 1, 1)
        self.ThresholdBSpinBox = QtWidgets.QSpinBox(self.AcqControlGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ThresholdBSpinBox.setFont(font)
        self.ThresholdBSpinBox.setMinimum(0)
        self.ThresholdBSpinBox.setMaximum(16383)
        self.ThresholdBSpinBox.setObjectName("ThresholdBSpinBox")
        self.gridLayout_7.addWidget(self.ThresholdBSpinBox, 6, 3, 1, 1)
        self.AcqNumberSpinBox = QtWidgets.QSpinBox(self.AcqControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AcqNumberSpinBox.sizePolicy().hasHeightForWidth())
        self.AcqNumberSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AcqNumberSpinBox.setFont(font)
        self.AcqNumberSpinBox.setSuffix("")
        self.AcqNumberSpinBox.setPrefix("")
        self.AcqNumberSpinBox.setMaximum(50000)
        self.AcqNumberSpinBox.setSingleStep(60)
        self.AcqNumberSpinBox.setProperty("value", 600)
        self.AcqNumberSpinBox.setObjectName("AcqNumberSpinBox")
        self.gridLayout_7.addWidget(self.AcqNumberSpinBox, 3, 3, 1, 1)
        self.ThresholdCSpinBox = QtWidgets.QSpinBox(self.AcqControlGroupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ThresholdCSpinBox.setFont(font)
        self.ThresholdCSpinBox.setMinimum(0)
        self.ThresholdCSpinBox.setMaximum(16383)
        self.ThresholdCSpinBox.setObjectName("ThresholdCSpinBox")
        self.gridLayout_7.addWidget(self.ThresholdCSpinBox, 6, 4, 1, 1)
        self.GainFrame = QtWidgets.QFrame(self.AcqControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GainFrame.sizePolicy().hasHeightForWidth())
        self.GainFrame.setSizePolicy(sizePolicy)
        self.GainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GainFrame.setObjectName("GainFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.GainFrame)
        self.horizontalLayout_8.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.GainCheckBox = QtWidgets.QCheckBox(self.GainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GainCheckBox.sizePolicy().hasHeightForWidth())
        self.GainCheckBox.setSizePolicy(sizePolicy)
        self.GainCheckBox.setObjectName("GainCheckBox")
        self.horizontalLayout_8.addWidget(self.GainCheckBox)
        self.GainSpinBox = QtWidgets.QDoubleSpinBox(self.GainFrame)
        self.GainSpinBox.setDecimals(4)
        self.GainSpinBox.setMaximum(1.0)
        self.GainSpinBox.setSingleStep(0.001)
        self.GainSpinBox.setProperty("value", 1.0)
        self.GainSpinBox.setObjectName("GainSpinBox")
        self.horizontalLayout_8.addWidget(self.GainSpinBox)
        self.gridLayout_7.addWidget(self.GainFrame, 7, 3, 1, 1)
        self.UpdateTimeSpinBox = QtWidgets.QDoubleSpinBox(self.AcqControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UpdateTimeSpinBox.sizePolicy().hasHeightForWidth())
        self.UpdateTimeSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UpdateTimeSpinBox.setFont(font)
        self.UpdateTimeSpinBox.setMinimum(0.25)
        self.UpdateTimeSpinBox.setMaximum(5.0)
        self.UpdateTimeSpinBox.setSingleStep(0.25)
        self.UpdateTimeSpinBox.setObjectName("UpdateTimeSpinBox")
        self.gridLayout_7.addWidget(self.UpdateTimeSpinBox, 3, 4, 1, 1)
        self.StopCriteriaComboBox = QtWidgets.QComboBox(self.AcqControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopCriteriaComboBox.sizePolicy().hasHeightForWidth())
        self.StopCriteriaComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.StopCriteriaComboBox.setFont(font)
        self.StopCriteriaComboBox.setObjectName("StopCriteriaComboBox")
        self.gridLayout_7.addWidget(self.StopCriteriaComboBox, 3, 1, 1, 1)
        self.StartStopAcqButton = QtWidgets.QPushButton(self.AcqControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartStopAcqButton.sizePolicy().hasHeightForWidth())
        self.StartStopAcqButton.setSizePolicy(sizePolicy)
        self.StartStopAcqButton.setObjectName("StartStopAcqButton")
        self.gridLayout_7.addWidget(self.StartStopAcqButton, 0, 1, 1, 1)
        self.ViewFrame = QtWidgets.QFrame(self.AcqControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ViewFrame.sizePolicy().hasHeightForWidth())
        self.ViewFrame.setSizePolicy(sizePolicy)
        self.ViewFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ViewFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ViewFrame.setObjectName("ViewFrame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.ViewFrame)
        self.horizontalLayout_12.setContentsMargins(10, 4, 4, 4)
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.SpectrumRadioButton = QtWidgets.QRadioButton(self.ViewFrame)
        self.SpectrumRadioButton.setObjectName("SpectrumRadioButton")
        self.horizontalLayout_12.addWidget(self.SpectrumRadioButton, 0, QtCore.Qt.AlignHCenter)
        self.ScalerRadioButton = QtWidgets.QRadioButton(self.ViewFrame)
        self.ScalerRadioButton.setObjectName("ScalerRadioButton")
        self.horizontalLayout_12.addWidget(self.ScalerRadioButton, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_7.addWidget(self.ViewFrame, 7, 4, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.AcqControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_24.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.AutoRestartCheckBox = QtWidgets.QCheckBox(self.frame_2)
        self.AutoRestartCheckBox.setObjectName("AutoRestartCheckBox")
        self.verticalLayout_24.addWidget(self.AutoRestartCheckBox, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_7.addWidget(self.frame_2, 7, 1, 1, 1)
        self.horizontalLayout_6.addWidget(self.AcqControlGroupBox)
        self.AcqStatusGroupBox = QtWidgets.QGroupBox(self.tab_sp_bottom_frame)
        self.AcqStatusGroupBox.setObjectName("AcqStatusGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.AcqStatusGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.IBar = QtWidgets.QProgressBar(self.AcqStatusGroupBox)
        self.IBar.setProperty("value", 24)
        self.IBar.setObjectName("IBar")
        self.gridLayout.addWidget(self.IBar, 4, 1, 1, 1)
        self.UBar = QtWidgets.QProgressBar(self.AcqStatusGroupBox)
        self.UBar.setProperty("value", 24)
        self.UBar.setObjectName("UBar")
        self.gridLayout.addWidget(self.UBar, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.AcqStatusGroupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.ProgressBar = QtWidgets.QProgressBar(self.AcqStatusGroupBox)
        self.ProgressBar.setProperty("value", 24)
        self.ProgressBar.setObjectName("ProgressBar")
        self.gridLayout.addWidget(self.ProgressBar, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.AcqStatusGroupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.AcqStatusGroupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.AcqStatusGroupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.DeadTimeBar = QtWidgets.QProgressBar(self.AcqStatusGroupBox)
        self.DeadTimeBar.setProperty("value", 24)
        self.DeadTimeBar.setObjectName("DeadTimeBar")
        self.gridLayout.addWidget(self.DeadTimeBar, 2, 1, 1, 1)
        self.horizontalLayout_6.addWidget(self.AcqStatusGroupBox)
        self.verticalLayout_20.addWidget(self.tab_sp_bottom_frame)
        self.Tabs.addTab(self.tab_SP, "")
        self.verticalLayout_4.addWidget(self.Tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuWaveform_Settings = QtWidgets.QMenu(self.menuFile)
        self.menuWaveform_Settings.setObjectName("menuWaveform_Settings")
        self.menuAcquisition_Settings = QtWidgets.QMenu(self.menuFile)
        self.menuAcquisition_Settings.setObjectName("menuAcquisition_Settings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setEnabled(True)
        self.actionExit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionExit.setObjectName("actionExit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.Save_WF_Settings = QtWidgets.QAction(MainWindow)
        self.Save_WF_Settings.setObjectName("Save_WF_Settings")
        self.Back_to_Saved_WF_Settings = QtWidgets.QAction(MainWindow)
        self.Back_to_Saved_WF_Settings.setObjectName("Back_to_Saved_WF_Settings")
        self.Back_to_Default_WF_Settings = QtWidgets.QAction(MainWindow)
        self.Back_to_Default_WF_Settings.setObjectName("Back_to_Default_WF_Settings")
        self.Save_ACQ_Settings = QtWidgets.QAction(MainWindow)
        self.Save_ACQ_Settings.setObjectName("Save_ACQ_Settings")
        self.Back_to_Saved_ACQ_Settings = QtWidgets.QAction(MainWindow)
        self.Back_to_Saved_ACQ_Settings.setObjectName("Back_to_Saved_ACQ_Settings")
        self.Back_to_Default_ACQ_Settings = QtWidgets.QAction(MainWindow)
        self.Back_to_Default_ACQ_Settings.setObjectName("Back_to_Default_ACQ_Settings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuWaveform_Settings.addAction(self.Save_WF_Settings)
        self.menuWaveform_Settings.addAction(self.Back_to_Saved_WF_Settings)
        self.menuWaveform_Settings.addAction(self.Back_to_Default_WF_Settings)
        self.menuAcquisition_Settings.addAction(self.Save_ACQ_Settings)
        self.menuAcquisition_Settings.addAction(self.Back_to_Saved_ACQ_Settings)
        self.menuAcquisition_Settings.addAction(self.Back_to_Default_ACQ_Settings)
        self.menuFile.addAction(self.menuWaveform_Settings.menuAction())
        self.menuFile.addAction(self.menuAcquisition_Settings.menuAction())
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(2)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Channel Select"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Firmware"))
        self.ROCFirmware.setText(_translate("MainWindow", "----"))
        self.AMCFirmware.setText(_translate("MainWindow", "----"))
        self.License.setText(_translate("MainWindow", "----"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Empty Box I"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Link number"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Connection type"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Channels"))
        self.Channels.setText(_translate("MainWindow", "----"))
        self.HVChannels.setText(_translate("MainWindow", "----"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Board Information"))
        self.SerialNumber.setText(_translate("MainWindow", "----"))
        self.ModelName.setText(_translate("MainWindow", "----"))
        self.FamilyCode.setText(_translate("MainWindow", "----"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Empty Box II"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Control connection"))
        self.Disconn.setText(_translate("MainWindow", "Disconnected"))
        self.Connect.setText(_translate("MainWindow", "Connect"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_CF), _translate("MainWindow", " Connection "))
        self.groupBox.setTitle(_translate("MainWindow", " Actual Voltage"))
        self.label.setText(_translate("MainWindow", "V"))
        self.Title_0.setText(_translate("MainWindow", "title1"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Limit Maximum Voltage to"))
        self.VMax.setSuffix(_translate("MainWindow", " V"))
        self.groupBox_5.setTitle(_translate("MainWindow", "CONTROL"))
        self.V_ON.setText(_translate("MainWindow", "ON"))
        self.V_OFF.setText(_translate("MainWindow", "OFF"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Limit Maximum Current to"))
        self.IMax.setSuffix(_translate("MainWindow", " μA"))
        self.Title_1.setText(_translate("MainWindow", "title2"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Set Voltage"))
        self.VSet.setSuffix(_translate("MainWindow", " V"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Set Ramp Up Speed to"))
        self.RampUp.setSuffix(_translate("MainWindow", " V/s"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Set Ramp Down Speed to"))
        self.RampDown.setSuffix(_translate("MainWindow", " V/s"))
        self.groupBox_3.setTitle(_translate("MainWindow", " Actual Current"))
        self.label_2.setText(_translate("MainWindow", "μA"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_HV), _translate("MainWindow", " High Voltage "))
        self.groupBox_10.setTitle(_translate("MainWindow", "Analog Input"))
        self.DCoffsetSpinBox.setSuffix(_translate("MainWindow", " %"))
        self.DCoffsetSpinBox.setPrefix(_translate("MainWindow", "DC Offset: "))
        self.FineGainSpinBox.setPrefix(_translate("MainWindow", "Fine gain: "))
        self.groupBox_19.setTitle(_translate("MainWindow", "Traces A, B, C"))
        self.groupBox_23.setTitle(_translate("MainWindow", "Digital Shaper"))
        self.RiseTimeSpinBox.setPrefix(_translate("MainWindow", "Rise Time:    "))
        self.RiseTimeSpinBox.setSuffix(_translate("MainWindow", " μs"))
        self.DecayTimeSpinBox.setPrefix(_translate("MainWindow", "Decay Time:   "))
        self.DecayTimeSpinBox.setSuffix(_translate("MainWindow", " μs"))
        self.FlatTopSpinBox.setPrefix(_translate("MainWindow", "Flat Top:     "))
        self.FlatTopSpinBox.setSuffix(_translate("MainWindow", " μs"))
        self.PeakDelaySpinBox.setPrefix(_translate("MainWindow", "Peak Delay:   "))
        self.PeakDelaySpinBox.setSuffix(_translate("MainWindow", " μs"))
        self.PeakHoldoffSpinBox.setPrefix(_translate("MainWindow", "Peak Holdoff: "))
        self.PeakHoldoffSpinBox.setSuffix(_translate("MainWindow", " μs"))
        self.BaseHoldoffSpinBox.setPrefix(_translate("MainWindow", "Base Holdoff: "))
        self.BaseHoldoffSpinBox.setSuffix(_translate("MainWindow", " μs"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Vertical A"))
        self.label_3.setText(_translate("MainWindow", "Scale"))
        self.label_4.setText(_translate("MainWindow", "Offset"))
        self.groupBox_25.setTitle(_translate("MainWindow", "Vertical B"))
        self.label_7.setText(_translate("MainWindow", "Scale"))
        self.label_8.setText(_translate("MainWindow", "Offset"))
        self.groupBox_22.setTitle(_translate("MainWindow", "Horizontal"))
        self.label_5.setText(_translate("MainWindow", "Scale"))
        self.label_6.setText(_translate("MainWindow", "Offset"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Trigger"))
        self.TriggerButton.setText(_translate("MainWindow", "Start"))
        self.TriggerRiseTime.setPrefix(_translate("MainWindow", "Rise Time: "))
        self.TriggerRiseTime.setSuffix(_translate("MainWindow", " μs"))
        self.TriggerHoldoff.setPrefix(_translate("MainWindow", "Holdoff:   "))
        self.TriggerHoldoff.setSuffix(_translate("MainWindow", " μs"))
        self.TriggerIntro.setPrefix(_translate("MainWindow", "Intro:     "))
        self.TriggerIntro.setSuffix(_translate("MainWindow", " μs"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_OS), _translate("MainWindow", " Oscilloscope "))
        self.LogScaleCheckBox.setText(_translate("MainWindow", "Log Scale"))
        self.ACheckBox.setText(_translate("MainWindow", "Rate A"))
        self.BCheckBox.setText(_translate("MainWindow", "Rate B"))
        self.CCheckBox.setText(_translate("MainWindow", "Rate C"))
        self.AcqControlGroupBox.setTitle(_translate("MainWindow", "Acquisition Control"))
        self.ClearAcqButton.setText(_translate("MainWindow", "Clear"))
        self.ThresholdASpinBox.setSuffix(_translate("MainWindow", " ch"))
        self.ThresholdASpinBox.setPrefix(_translate("MainWindow", "Threshold A: "))
        self.SaveAcqButton.setText(_translate("MainWindow", "Save"))
        self.ThresholdBSpinBox.setSuffix(_translate("MainWindow", " ch"))
        self.ThresholdBSpinBox.setPrefix(_translate("MainWindow", "Threshold B: "))
        self.ThresholdCSpinBox.setSuffix(_translate("MainWindow", " ch"))
        self.ThresholdCSpinBox.setPrefix(_translate("MainWindow", "Threshold C: "))
        self.GainCheckBox.setText(_translate("MainWindow", "Gain"))
        self.GainSpinBox.setSuffix(_translate("MainWindow", " keV/ch"))
        self.UpdateTimeSpinBox.setPrefix(_translate("MainWindow", "Update time "))
        self.UpdateTimeSpinBox.setSuffix(_translate("MainWindow", " s"))
        self.StartStopAcqButton.setText(_translate("MainWindow", "Start"))
        self.SpectrumRadioButton.setText(_translate("MainWindow", "Spectrum "))
        self.ScalerRadioButton.setText(_translate("MainWindow", "Scaler "))
        self.AutoRestartCheckBox.setText(_translate("MainWindow", "Cycle Acquisition"))
        self.AcqStatusGroupBox.setTitle(_translate("MainWindow", "Acquisition Status"))
        self.label_10.setText(_translate("MainWindow", "High Voltage:"))
        self.label_12.setText(_translate("MainWindow", "HV Current:"))
        self.label_11.setText(_translate("MainWindow", "Progress:"))
        self.label_9.setText(_translate("MainWindow", "Dead time :"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_SP), _translate("MainWindow", " Acquisition "))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuWaveform_Settings.setTitle(_translate("MainWindow", "Waveform Settings"))
        self.menuAcquisition_Settings.setTitle(_translate("MainWindow", "Acquisition Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit Application"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.Save_WF_Settings.setText(_translate("MainWindow", "Save"))
        self.Back_to_Saved_WF_Settings.setText(_translate("MainWindow", "Back to Saved"))
        self.Back_to_Default_WF_Settings.setText(_translate("MainWindow", "Back to Default"))
        self.Save_ACQ_Settings.setText(_translate("MainWindow", "Save"))
        self.Back_to_Saved_ACQ_Settings.setText(_translate("MainWindow", "Back to Saved"))
        self.Back_to_Default_ACQ_Settings.setText(_translate("MainWindow", "Back to Default"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
from TABs.Canvas import AcqCanvas
from TABs.Scope import OscCanvas
